use carteDB;

/*TOTUL DESPRE CONSTRAINTS*/

CREATE TABLE Artist(
ArtistId INTEGER NOT NULL IDENTITY(1,1) PRIMARY KEY,
Nume VARCHAR(255) NOT NULL UNIQUE,
Varsta INTEGER NOT NULL CHECK (Varsta>=18),
Oras VARCHAR(255) DEFAULT 'Bucuresti',
CONSTRAINT UK_Persoana UNIQUE (ArtistId, Nume) 
/*LA FEL SI CU MULTIPLE PRIMARY KEY*/
/* PRIMARY KEY=NOT NULL + UNIQUE*/
);

CREATE TABLE Album(
AlbumId INTEGER,
Nume VARCHAR(255),
Data_Publicare Date,
ArtistId INTEGER FOREIGN KEY REFERENCES Artist(ArtistId)
);

ALTER TABLE Album
ALTER COLUMN AlbumId INTEGER NOT NULL;

ALTER TABLE Album
ADD UNIQUE (Nume);

ALTER TABLE Album
ADD CONSTRAINT UQ_Album UNIQUE (AlbumId,Nume);

ALTER TABLE Album
DROP CONSTRAINT UQ_Album;
/* POTI PUNE DROP DOAR LA CONSTRAINTS*/

ALTER TABLE Album
ADD PRIMARY KEY (AlbumId);

ALTER TABLE Album
ADD CHECK (Data_Publicare>='20-02-1900');