CREATE DATABASE testDB; 
/* CREEAZA O BAZA DE DATE CU ACEL NUME*/



BACKUP DATABASE testDB
TO DISK = 'C:\Software Developer\FACTURI\testDB.bak';
/*BACKING UP PE DISK BAZA DE DATE*/


DROP DATABASE testDB;
/*STERGE BAZA DE DATE CU ACEL NUME*/